//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class RandomSingleton
	{
		public Random random;
		private static RandomSingleton instance = null;

		public RandomSingleton ()
		{
			random = new Random ();
		}

		public static RandomSingleton getInstance()
		{
			if (instance == null)
			{
				instance = new RandomSingleton ();
			}
			return instance;
		}
	}
}

